name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      
    - name: Rust Release binary
      uses: rust-build/rust-build.action@v1.3.2
      with:
        # Output target
        RUSTTARGET: vscode-git-bridge
        TOOLCHAIN_VERSION: stable-x86_64-pc-windows-msvc
        UPLOAD_MODE: release
